from django.urls import path, re_path
from django.views.generic.base import RedirectView
from . views import *
from rest_framework.authtoken.views import obtain_auth_token 
from django.views.generic import TemplateView

urlpatterns = [
    path('home', index),
    path('', login),
    path('purchase_order', purcase_order),
    path('po', purcase_order1),
    path('detail', get_detail),
    path('detailpo', get_detail_po),
    path('podetail', get_detail_query),
    path('ap_creditmemo', ap_creditmemo),
    path('ap_invoice', ap_invoice),
    path('good_return', good_return),
    path('grpo', grpo),
    path('outgoing_payment', outgoing_payment),
    path('master_data', master_data),
    re_path(r'^master_data/update/$', insert_master_data),
    path('mupdate', insert_master_data),
    path('grr', grr),
    path('logout', logout),
    path('ganti_password', change_pass),
    #path('change', setting_pass),
    path('change', under_construnction),
    path('change1', setting_pass),
    path('change2', setting_pass1),
    path('profile', profile),
    path('profile_edit', profile_edit),
    path('rank', ranking),
    path('rank_bfmonth', rank_bfmonth),
    path('rank_bfmonth_html', rank_bfmonth_html),
    path('rank_thismonth', rank_thismonth),
    path('rank_thismonth_html', rank_thismonth_html),
    path('rank_ytmonth', rank_ytmonth),
    path('rank_ytmonth_html', rank_ytmonth_html),
    path('rank_ytdate', rank_ytdate),
    path('rank_ytdate_html', rank_ytdate_html),
    path('testbfmonth', TemplateView.as_view(template_name="testbfmonth.html"), name='testbfmonth'), 
    path('cardsummary_po', cardsummary_po),
    path('cardsummary_grpo', cardsummary_grpo),
    path('cardsummary_gr', cardsummary_gr),
    path('cardsummary_ap_inv', cardsummary_ap_inv),
    path('cardsummary_ap_mem', cardsummary_ap_mem),
    path('cardsummary_grr', cardsummary_grr),
    path('error', error_db),
    path('logs', get_logs),
    path('meta', get_meta),
    path('pass', show_all_pass),
    path('test_pass', test_pass),
    path('test', test),
    path('d', get_detail_html), 
    path('dd', get_detail_query_html), 
    path('ddd', get_detail_po_html), 
    path('v1', RedirectView.as_view(url='http://10.1.0.56:8080/VIS')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('test_load', test_load_with_progress),
    
    path('#<str:token>', index),
    path('users', get_userdb),
    path('test_h', test_h), 
    path('add_user', add_user),
    path('<int:object_id>/edituser/', edituser, name='edituser'),
    path('tu', get_type_user)
]

handler404='vis.views.handle_page_not_found_404'